# Generated by Django 4.1.13 on 2024-02-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('option_a', models.TextField(default='')),
                ('option_b', models.TextField(default='')),
                ('option_c', models.TextField(default='')),
                ('option_d', models.TextField(default='')),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
    ]
